language: python
matrix:
    include:
        - os: linux
          sudo: required
          python: 2.7
          env: TOXENV=py27
        - os: linux
          sudo: required
          python: 3.6
          env: TOXENV=py36
        - os: osx
          language: generic
          env: TOXENV=py27
        - os: osx
          language: generic
          env: TOXENV=py36

cache: pip
before_install:  |
  if [ $TRAVIS_OS_NAME = linux ]; then
    sudo apt-get install -y libopenblas-dev
  else
    if [ $TOXENV = py27 ]
    then
	brew install python@2
	export PATH=/usr/local/opt/python2:$PATH
    elif [ $TOXENV = py36 ]
    then
	brew uninstall --ignore-dependencies python
	brew install python@3

	export PATH=/usr/local/opt/python3:$PATH
	ln -s /usr/local/opt/python3/bin/python3 /usr/local/opt/python3/bin/python
    fi
  fi

install:
  - pip install -r requirements.txt
script:
  - python test_tau_calculator.py
  - python test_interpolation.py
  - python test_retrieve.py
  - python test_transit_depth_calculator.py
