language: python
matrix:
    include:
        - os: linux
          sudo: required
          python: 2.7
          env: TOXENV=py27
        - os: linux
          sudo: required
          python: 3.6
          env: TOXENV=py36
        - os: osx
          language: generic
          env: TOXENV=py27
        - os: osx
          language: generic
          env: TOXENV=py36

cache: pip
before_install:  |
  if [ $TRAVIS_OS_NAME = linux ]; then
    sudo apt-get install -y libopenblas-dev
  else
    brew update
    if [ $TOXENV = py27 ]
    then
       curl https://bootstrap.pypa.io/get-pip.py | sudo python
    elif [ $TOXENV = py36 ]
    then
       brew upgrade python
       alias python=python3
       curl https://bootstrap.pypa.io/get-pip.py | sudo python3
    fi

  fi

install:
  - pip install -r requirements.txt --user
script:
  - python test_tau_calculator.py
  - python test_interpolation.py
  - python test_retrieve.py
  - python test_transit_depth_calculator.py
