language: python
python:
  - "2.7"
  - "3.6"
cache: pip
before_install:
  - sudo apt-get install -y libopenblas-dev libopenblas-base
install:
  - pip install -r requirements.txt 
script:
  - python test_tau_calculator.py
  - python test_interpolation.py
  - python test_retrieve.py
  - python test_transit_depth_calculator.py
