language: python
matrix:
    include:
        - os: linux
          sudo: required
          python: 2.7
          env: TOXENV=py27
        - os: linux
          sudo: required
          python: 3.6
          env: TOXENV=py36
        - os: osx
          language: generic
          env: TOXENV=py27
        - os: osx
          language: generic
          env: TOXENV=py36

cache: pip
before_install:  |
  if [ $TRAVIS_OS_NAME = linux ]; then
    sudo apt-get install -y libopenblas-dev
  else
    brew update
    case "${TOXENV}" in
        py27)
	    brew install python
	    virtualenv venv -p python
        py36)
	    brew install python3
	    virtualenv venv -p python3
    esac

    source venv/bin/activate
    brew install openblas
  fi

install:
  - pip install -r requirements.txt 
script:
  - python test_tau_calculator.py
  - python test_interpolation.py
  - python test_retrieve.py
  - python test_transit_depth_calculator.py
