language: python
python:
  - "2.7"
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt 
script:
  - python test_tau_calculator.py
  - python test_interpolation.py
  - python retrieve_example.py

