language: python
python:
  - "2.7"
  - "3.6"
os:
  - linux
  - osx
cache: pip
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y libopenblas-dev; else brew install openblas; fi

install:
  - pip install -r requirements.txt 
script:
  - python test_tau_calculator.py
  - python test_interpolation.py
  - python test_retrieve.py
  - python test_transit_depth_calculator.py
